import type { Metadata, Viewport } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { Toaster } from "@gifteeng/ui";
import "./globals.css";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://new.gifteeng.com";

// Single bundled latin subset — keeps the font fetch under 35KB and
// avoids the 1.4MB Cyrillic / Greek payload Google would otherwise
// serve. Both fonts use display:swap so we never block paint.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-display",
  display: "swap",
});

// ── Metadata: title template + canonical + OG/Twitter defaults ──────────
//
// `metadataBase` resolves any relative `openGraph.images` URL to absolute,
// which Slack / WhatsApp / iMessage previews need. The `template` lets
// child pages set just `title:` and Next stitches "X | Gifteeng" so we
// never have to repeat the brand suffix.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default:  "Gifteeng — India's Premium Personalized Gifts | Custom Photo Frames, Mugs, Keychains",
    template: "%s | Gifteeng",
  },
  description:
    "Handcrafted, personalized gifts delivered across India — custom photo frames, mugs, keychains, name plates, and more. Starting ₹99. Free shipping on orders over ₹499.",
  keywords: [
    "personalized gifts India",
    "custom photo gifts",
    "personalized mugs",
    "custom photo frames",
    "personalized keychains",
    "name plates",
    "corporate gifts",
    "anniversary gifts",
    "birthday gifts",
    "wedding gifts",
    "Mother's Day gifts",
    "Father's Day gifts",
    "gift personalization",
    "Gifteeng",
  ],
  authors:  [{ name: "Gifteeng", url: SITE_URL }],
  creator:  "Gifteeng",
  publisher:"Gifteeng",
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    type:        "website",
    siteName:    "Gifteeng",
    locale:      "en_IN",
    url:         SITE_URL,
    title:       "Gifteeng — India's Premium Personalized Gifts",
    description: "Handcrafted, personalized gifts delivered across India. Custom photo frames, mugs, keychains, and more — starting ₹99.",
    images: [
      {
        // Dynamically generated by app/opengraph-image.tsx — always
        // matches the brand wordmark/palette without a static asset to
        // maintain. Child route segments can ship their own
        // opengraph-image.tsx to override (product detail does this).
        url:    "/opengraph-image",
        width:  1200,
        height: 630,
        alt:    "Gifteeng — Personalized gifts for every occasion",
      },
    ],
  },
  twitter: {
    card:        "summary_large_image",
    site:        "@gifteeng",
    creator:     "@gifteeng",
    title:       "Gifteeng — India's Premium Personalized Gifts",
    description: "Handcrafted, personalized gifts delivered across India.",
    images:      ["/opengraph-image"],
  },
  robots: {
    index:      true,
    follow:     true,
    nocache:    false,
    googleBot: {
      index:                true,
      follow:               true,
      noimageindex:         false,
      "max-snippet":        -1,
      "max-image-preview":  "large",
      "max-video-preview":  -1,
    },
  },
  formatDetection: {
    email:     false,
    address:   false,
    telephone: false,
  },
  applicationName: "Gifteeng",
  category: "shopping",
  // App store cross-links so iOS Safari / Android Chrome surface a
  // "Get the Gifteeng app" smart banner. URLs are also driven by the
  // marketing_config admin page; these are the deterministic fallbacks.
  appleWebApp: {
    capable:   true,
    title:     "Gifteeng",
    statusBarStyle: "black-translucent",
  },
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#EF3752",
  // Render the safe-area / notch in the brand colour, so iPhone X+
  // doesn't show a default-white strip when the page background scrolls.
  colorScheme: "light dark",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // ── Site-wide JSON-LD ─────────────────────────────────────────────
  // Organization + WebSite + SearchAction. Google's rich-results
  // crawler reads these to surface the brand sitelinks search box and
  // the storefront knowledge panel.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type":  "Organization",
        "@id":    `${SITE_URL}/#organization`,
        "name":   "Gifteeng",
        "url":    SITE_URL,
        "logo":   `${SITE_URL}/icon.svg`,
        "sameAs": [
          "https://www.instagram.com/gifteeng",
          "https://www.facebook.com/gifteeng",
        ],
        "contactPoint": [{
          "@type":         "ContactPoint",
          "email":         "support@gifteeng.com",
          "contactType":   "customer support",
          "areaServed":    "IN",
          "availableLanguage": ["en", "hi"],
        }],
      },
      {
        "@type":     "WebSite",
        "@id":       `${SITE_URL}/#website`,
        "url":       SITE_URL,
        "name":      "Gifteeng",
        "publisher": { "@id": `${SITE_URL}/#organization` },
        "inLanguage":"en-IN",
        "potentialAction": {
          "@type":  "SearchAction",
          "target": {
            "@type":       "EntryPoint",
            "urlTemplate": `${SITE_URL}/search?q={search_term_string}`,
          },
          "query-input": "required name=search_term_string",
        },
      },
    ],
  };

  return (
    <html lang="en-IN" className={`${inter.variable} ${plusJakarta.variable}`}>
      <head>
        {/* DNS pre-resolve for the API origin so the first /api/* request
            doesn't pay the 50–150ms DNS+TLS handshake. */}
        <link rel="dns-prefetch" href="//new-api.gifteeng.com" />
        <link rel="preconnect"   href="https://new-api.gifteeng.com" crossOrigin="anonymous" />

        {/* Anti-FOUC: apply theme class before first paint */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{var t=localStorage.getItem('gifteeng.theme')||'light';var d=t==='dark'||(t==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches);if(d)document.documentElement.classList.add('dark-premium');}catch(e){}`,
          }}
        />

        {/* Site-wide JSON-LD — rendered server-side so crawlers see it
            without executing JS. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-screen bg-background text-foreground antialiased font-body">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
