import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { Rubik, Nunito_Sans } from "next/font/google";
import { Toaster } from "@gifteeng/ui";
import "./globals.css";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://gifteeng.com";

// UI/UX Pro Max design system recommendation for Gifteeng (e-commerce gifting):
//   Heading → Rubik  (bold, warm, playful — perfect for a gifting brand)
//   Body    → Nunito Sans  (clean, readable, friendly — boosts e-commerce trust)
// Both use latin subset + display:swap so we never block paint.
// Weight 300–800 covers all UI states (light subtitles → black headings).
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-display",
  display: "swap",
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-inter",
  display: "swap",
});

// ── Metadata: title template + canonical + OG/Twitter defaults ──────────
//
// `metadataBase` resolves any relative `openGraph.images` URL to absolute,
// which Slack / WhatsApp / iMessage previews need. The `template` lets
// child pages set just `title:` and Next stitches "X | Gifteeng" so we
// never have to repeat the brand suffix.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default:  "Gifteeng — Personalized Gifts India",
    template: "%s",
  },
  description:
    "Shop personalized gifts in India — custom photo frames, mugs, keychains & more. Starting ₹99. Free delivery on orders ₹499+.",
  keywords: [
    "personalized gifts India",
    "custom photo gifts",
    "personalized mugs",
    "custom photo frames",
    "personalized keychains",
    "name plates",
    "corporate gifts",
    "anniversary gifts",
    "birthday gifts",
    "wedding gifts",
    "Mother's Day gifts",
    "Father's Day gifts",
    "gift personalization",
    "Gifteeng",
  ],
  authors:  [{ name: "Gifteeng", url: SITE_URL }],
  creator:  "Gifteeng",
  publisher:"Gifteeng",
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    type:        "website",
    siteName:    "Gifteeng",
    locale:      "en_IN",
    url:         SITE_URL,
    title:       "Gifteeng — India's Premium Personalized Gifts",
    description: "Handcrafted, personalized gifts delivered across India. Custom photo frames, mugs, keychains, and more — starting ₹99.",
    images: [
      {
        // Dynamically generated by app/opengraph-image.tsx — always
        // matches the brand wordmark/palette without a static asset to
        // maintain. Child route segments can ship their own
        // opengraph-image.tsx to override (product detail does this).
        url:    "/opengraph-image",
        width:  1200,
        height: 630,
        alt:    "Gifteeng — Personalized gifts for every occasion",
      },
    ],
  },
  twitter: {
    card:        "summary_large_image",
    site:        "@gifteeng",
    creator:     "@gifteeng",
    title:       "Gifteeng — India's Premium Personalized Gifts",
    description: "Handcrafted, personalized gifts delivered across India.",
    images:      ["/opengraph-image"],
  },
  robots: {
    index:      true,
    follow:     true,
    nocache:    false,
    googleBot: {
      index:                true,
      follow:               true,
      noimageindex:         false,
      "max-snippet":        -1,
      "max-image-preview":  "large",
      "max-video-preview":  -1,
    },
  },
  formatDetection: {
    email:     false,
    address:   false,
    telephone: false,
  },
  applicationName: "Gifteeng",
  category: "shopping",
  // App store cross-links so iOS Safari / Android Chrome surface a
  // "Get the Gifteeng app" smart banner. URLs are also driven by the
  // marketing_config admin page; these are the deterministic fallbacks.
  appleWebApp: {
    capable:   true,
    title:     "Gifteeng",
    statusBarStyle: "black-translucent",
  },
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#EF3752",
  // Render the safe-area / notch in the brand colour, so iPhone X+
  // doesn't show a default-white strip when the page background scrolls.
  colorScheme: "light dark",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // CSP nonce — set by middleware.ts and read here so inline <script>
  // blocks below can carry `nonce={nonce}` and execute under the strict
  // CSP. Without this they'd be silently blocked by the browser. See
  // docs/SECURITY_AUDIT.md M-3.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  // ── Site-wide JSON-LD ─────────────────────────────────────────────
  // Organization + WebSite + SearchAction. Google's rich-results
  // crawler reads these to surface the brand sitelinks search box and
  // the storefront knowledge panel.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type":  "Organization",
        "@id":    `${SITE_URL}/#organization`,
        "name":   "Gifteeng",
        "url":    SITE_URL,
        "logo":   `${SITE_URL}/icon.svg`,
        "sameAs": [
          "https://www.instagram.com/gifteeng",
          "https://www.facebook.com/gifteeng",
          "https://www.youtube.com/@gifteeng",
          "https://www.linkedin.com/company/gifteeng",
        ],
        "aggregateRating": {
          "@type":       "AggregateRating",
          "ratingValue": "4.5",
          "reviewCount": "5000",
          "bestRating":  "5",
          "worstRating": "1",
        },
        "contactPoint": [{
          "@type":         "ContactPoint",
          "email":         "support@gifteeng.com",
          "telephone":     "+918070011777",
          "contactType":   "customer support",
          "areaServed":    "IN",
          "availableLanguage": ["en", "hi"],
        }],
      },
      {
        "@type":     "WebSite",
        "@id":       `${SITE_URL}/#website`,
        "url":       SITE_URL,
        "name":      "Gifteeng",
        "publisher": { "@id": `${SITE_URL}/#organization` },
        "inLanguage":"en-IN",
        "potentialAction": {
          "@type":  "SearchAction",
          "target": {
            "@type":       "EntryPoint",
            "urlTemplate": `${SITE_URL}/b2c/search?q={search_term_string}`,
          },
          "query-input": "required name=search_term_string",
        },
      },
    ],
  };

  return (
    <html lang="en-IN" className={`${nunitoSans.variable} ${rubik.variable}`}>
      <head>
        {/* DNS pre-resolve for the API origin so the first /api/* request
            doesn't pay the 50–150ms DNS+TLS handshake. */}
        {/* Apple touch icon for iOS home screen / bookmarks */}
        <link rel="apple-touch-icon" href="/pwa-192x192.png" />

        <link rel="dns-prefetch" href="//api.gifteeng.com" />
        <link rel="preconnect"   href="https://api.gifteeng.com" crossOrigin="anonymous" />
        {/* Also pre-connect legacy subdomain during migration */}
        <link rel="dns-prefetch" href="//new-api.gifteeng.com" />
        {/* Pre-connect third-party origins used for analytics / ads */}
        <link rel="preconnect"   href="https://www.googletagmanager.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="//www.googletagmanager.com" />
        <link rel="preconnect"   href="https://connect.facebook.net" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="//connect.facebook.net" />

        {/* Anti-FOUC: apply theme class before first paint */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `try{var t=localStorage.getItem('gifteeng.theme')||'light';var d=t==='dark'||(t==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches);if(d)document.documentElement.classList.add('dark-premium');}catch(e){}`,
          }}
        />

        {/* Site-wide JSON-LD — rendered server-side so crawlers see it
            without executing JS. JSON-LD type=application/ld+json is
            harmless under CSP (browsers don't execute it as JS), but we
            still nonce it for consistency. */}
        <script
          type="application/ld+json"
          nonce={nonce}
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-screen bg-background text-foreground antialiased font-body">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
