#!/usr/bin/env bash
# Deploy session 85 — Flutter: feature parity with web SEO overhaul
#
# What ships:
#
#   PRODUCT DETAIL SCREEN
#   ─────────────────────
#   NEW  FAQ accordion section
#        Reads product.metadata.seo.faq (AI-generated by SeoEnrichmentService)
#        5 expandable tiles: customization · delivery · occasions · price · product-specific
#        Matches the FAQPage JSON-LD schema on the web (People Also Ask eligible)
#        Placed after Specifications, before Tags
#
#   HOME SCREEN
#   ───────────
#   UPD  OccasionChips → OccasionScroll
#        Now fetches live category data from /categories API
#        Circular image cards with coloured ring accent per category
#        Falls back gracefully to static emoji list when API is unavailable
#        Skeleton shimmer while loading (matches web OccasionScroll.tsx)
#
#   UPD  _TrustBar → _CompactStatsBar
#        Was: 4 tiny icon+label columns
#        Now: 3 bold stat cells — 3,00,000+ Gifts · 4.8⭐ Rating · 24 Hrs Dispatch
#        Bordered card container matching web CompactStatsBar.tsx
#
#   NEW  HowItWorksSection (how_it_works_section.dart)
#        3-step horizontal flow: Choose a Gift → Personalise It → Gift Delivered
#        Coloured circle icons + step badges, animated on scroll
#        Placed after OccasionScroll, before CategoryBento
#        Matches web HowItWorksSection.tsx
#
#   NEW  UgcSection (ugc_section.dart)
#        "Real Gifts. Real People. Real Smiles. 💛"
#        Horizontal scroll of gift-type cards
#        Full-width gradient CTA: "Create Your Gift Story"
#        Placed after CasinoBanner, before Marketplace stores
#        Matches web UGCWallSection.tsx
#
# Run on server as root:
#   bash /tmp/deploy-session85.sh

set -euo pipefail
log()  { echo ""; echo "==> $*"; }
ok()   { echo "  ✅ $*"; }
fail() { echo "  ❌ $*"; exit 1; }

PATCH=/tmp/patch_session85.tar.gz
DIR=/srv/gifteeng

if [[ ! -f "$PATCH" ]]; then
  fail "$PATCH not found — scp it first:
    scp deploy/patch_session85.tar.gz root@217.216.59.87:/tmp/"
fi

log "Extracting patch…"
cd "$DIR"
tar xzf "$PATCH"
ok "Files extracted"

# Flutter is not built on the server — the app is distributed as APK/IPA.
# This script just places the updated .dart source so the next CI/CD
# build or local developer build picks it up.
#
# If you have a Flutter build runner on this server:
#   cd /srv/gifteeng/apps/mobile && flutter build apk --release

log "Verifying extracted Flutter files…"
for f in \
  "apps/mobile/lib/features/shop/presentation/screens/product_detail_screen.dart" \
  "apps/mobile/lib/features/home/presentation/widgets/occasion_chips.dart" \
  "apps/mobile/lib/features/home/presentation/widgets/how_it_works_section.dart" \
  "apps/mobile/lib/features/home/presentation/widgets/ugc_section.dart" \
  "apps/mobile/lib/features/home/presentation/screens/home_screen.dart"; do
  if [[ -f "$DIR/$f" ]]; then
    ok "$f"
  else
    echo "  ⚠️  $f not found after extraction"
  fi
done

echo ""
echo "════════════════════════════════════════════════"
echo "  SESSION 85 — FLUTTER SEO PARITY DEPLOYED ✅"
echo "════════════════════════════════════════════════"
echo ""
echo "  What users now see in the app:"
echo "    ❓  Product FAQ accordion (AI-generated answers)"
echo "    🎯  Occasion cards with real category images from API"
echo "    📊  Compact stats: 3L+ gifts · 4.8★ · 24 Hrs dispatch"
echo "    ✨  How Gifteeng Works: 3-step visual flow"
echo "    💛  UGC wall: Real Gifts. Real People. Real Smiles."
echo ""
echo "  Next: build & release APK"
echo "    cd /srv/gifteeng/apps/mobile"
echo "    flutter build apk --release"
echo ""
