#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# Gifteeng deploy — replaces the hand-typed tar | scp | ssh dance.
# ─────────────────────────────────────────────────────────────────────────
#
# Usage:
#   scripts/deploy.sh <session_name> <file1> [file2] [file3] ...
#
# Example:
#   scripts/deploy.sh hotfix-cart \
#     apps/api/src/modules/cart/cart.service.ts \
#     apps/web/lib/stores/cart.ts
#
# What it does:
#   1. tar czf the listed files into /tmp/patch_<session>.tar.gz
#   2. scp the tarball + the matching deploy/deploy-<session>.sh to the VPS
#   3. ssh + run the remote deploy script
#   4. tail the result and exit with the script's status
#
# Variables:
#   VPS    — host (default 217.216.59.87)
#   USER   — SSH user (default root)
#
# If no `deploy/deploy-<session>.sh` exists yet, this script writes a
# default one that does:
#   tar xzf the patch, runs prisma migrate deploy if migrations changed,
#   pnpm builds api+web, restarts services, health-checks, prints
#   DEPLOY_OK <session>.

set -euo pipefail

VPS="${VPS:-217.216.59.87}"
USER="${USER:-root}"

if [[ $# -lt 2 ]]; then
  cat <<USAGE
Usage: scripts/deploy.sh <session_name> <file1> [file2] ...

  session_name   identifier used for the tarball + deploy script
                 (will look for deploy/deploy-<session_name>.sh)
  files          relative paths from the repo root to include in the
                 patch. Pass directories to include everything inside.

Examples:
  # Single hotfix
  scripts/deploy.sh hotfix-cart apps/api/src/modules/cart/cart.service.ts

  # Multi-file change
  scripts/deploy.sh feat-checkout \\
    apps/api/src/modules/checkout/checkout.service.ts \\
    apps/web/app/b2c/checkout/page.tsx
USAGE
  exit 2
fi

SESSION="$1"
shift

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PATCH="/tmp/patch_${SESSION}.tar.gz"
DEPLOY_SCRIPT="${ROOT}/deploy/deploy-${SESSION}.sh"

# ── Auto-generate a default deploy script if none exists ─────────────────
if [[ ! -f "$DEPLOY_SCRIPT" ]]; then
  echo "==> No deploy/deploy-${SESSION}.sh found — generating default."
  mkdir -p "${ROOT}/deploy"
  cat > "$DEPLOY_SCRIPT" <<EOF
#!/usr/bin/env bash
# ${SESSION} — auto-generated by scripts/deploy.sh
set -euo pipefail
cd /srv/gifteeng
set -a; . /srv/gifteeng/.env; set +a

tar xzf /tmp/patch_${SESSION}.tar.gz

# Apply Prisma migrations if any new ones landed
if [[ -d packages/db/prisma/migrations ]]; then
  echo "==> applying Prisma migrations..."
  (cd packages/db && pnpm prisma migrate deploy 2>&1 | tail -8) || \\
    echo "WARN: migrate deploy returned non-zero, proceeding"
  (cd packages/db && pnpm prisma generate 2>&1 | tail -3)
fi

# Builds
pnpm --filter @gifteeng/api build 2>&1 | tail -5
pnpm --filter @gifteeng/web build 2>&1 | tail -5

# Restart + health check
systemctl restart gifteeng-api
sleep 4
for i in 1 2 3 4 5 6; do
  if curl -fsS http://127.0.0.1:4000/api/health >/dev/null 2>&1; then
    echo "  api /health ok"; break
  fi
  echo "  ... api not ready (attempt \$i/6)"
  sleep 2
done
systemctl restart gifteeng-web
sleep 3
curl -fsS -o /dev/null -w 'web HTTP %{http_code}\\n' http://127.0.0.1:3000/

echo "DEPLOY_OK ${SESSION}"
EOF
  chmod +x "$DEPLOY_SCRIPT"
fi

# ── Build patch tarball ──────────────────────────────────────────────────
echo "==> Packing patch..."
# tar fails fast on missing files; if we listed `apps/api/package.json` and
# the dep just got bumped locally, this catches it.
tar czf "$PATCH" "$@"
SIZE=$(du -h "$PATCH" | cut -f1)
echo "    $PATCH ($SIZE)"

# ── Ship + deploy ────────────────────────────────────────────────────────
echo "==> scp $PATCH + $DEPLOY_SCRIPT → $USER@$VPS:/tmp/"
scp -o ConnectTimeout=10 "$PATCH" "$DEPLOY_SCRIPT" "$USER@$VPS:/tmp/"

echo "==> running /tmp/deploy-${SESSION}.sh on $VPS"
ssh -o ConnectTimeout=10 "$USER@$VPS" "bash /tmp/deploy-${SESSION}.sh" 2>&1 | tee "/tmp/deploy-${SESSION}.log"

# ── Status ───────────────────────────────────────────────────────────────
if grep -q "DEPLOY_OK ${SESSION}" "/tmp/deploy-${SESSION}.log"; then
  echo
  echo "✅ DEPLOY_OK ${SESSION}"
  exit 0
else
  echo
  echo "❌ Deploy did not report DEPLOY_OK. Tail of remote output:"
  tail -20 "/tmp/deploy-${SESSION}.log"
  exit 1
fi
